### ISSUE TITLE
Move ui modules to their own project

### ISSUE THREAD

**Issue by ianmcburnie** [makeup/makeup-js#153]
Related issue: https://github.com/makeup/makeup-js/issues/138

The UI modules (vanilla js implementations of MIND/Skin patterns) have always been in a more experimental state than the core modules, and even besides that I think organizationally it makes sense to separate them.

So the organization could look like this:

makeup-a11y -> core a11y modules
makeup-ui -> implementations of MIND/Skin
makeup-web-components -> web component wrappers around makeup-ui

We could possibly also have:

makeup-web-components-php -> php wrappers around SSR web components

(using PHP just as an example, but could be Marko, JSP, anything really)

**Comment by patricknelson** [comment]
In order to accomplish this, would you try to retain commit history for the new `makeup-ui` repository? Maybe either fork or just create a new bare repo and then push this repo over it, then make subsequent edits in both repos in order to trim the other packages out?

e.g. I assume you might:

1. Rename `makeup-js` to `makeup-a11y` (just to pick one) and then strip out the UI-specific modules.
2. Take this repo and push to new bare repository called `makeup-ui` and then strip out the core a11y logic modules.
3. Keep `makeup-web-components` as is? (since it already exists)

Alternatively (just to throw out an alternative option), one could also potentially nest into subfolders like:

```
packages/
  a11y\
    makeup-active-descendant\
    ...
  ui\
    makeup-alert-dialog\
    ...
  web-components\
    makeup-switch-element\
    ...
```

🤔

**Comment by ianmcburnie** [comment]
> In order to accomplish this, would you try to retain commit history for the new makeup-ui repository?

I don't mind losing the commit history for the UI portion to be honest. But I think the subfolders that you mention is probably the easiest. Given that that web-components inherit from ui and ui inherits from core, that is probably going to make the DX a little easier than having them in separate projects, right?

**Comment by patricknelson** [comment]
For me, it’s all about commit history. 😊 I need to know who to blame (er, “ask”) when changes are made that I don’t understand or if I need to dissect the history/intent of a particular block of code. Constantly hitting “First commit” could be frustrating in this situation.

So, consensus is leaning towards subfolders, methinks!

**Comment by ianmcburnie** [comment]
Closing as wont fix. We are going to just create a subfolder under packages dir:

```
packages
  /core
  /ui
  /elements
```

names tbd.
